services:
  app:
    build:
      context: . 
    ports:
      - "8081:8080" 
    volumes:
      - /run/desktop/mnt/host/c/Users/stano/Desktop/navchannya/2kurs/web/lab6/bc2024-6:/bc2024-6 
      - /run/desktop/mnt/host/c/Users/stano/Desktop/navchannya/2kurs/web/lab6/bc2024-6/notes:/bc2024-6/notes 
      - /bc2024-6/node_modules 
    command: ["npx", "nodemon", "index.js", "--host", "0.0.0.0", "--port", "8080", "--cache", "notes"] 
